version: "3.9"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
     - .env
    ports:
      - ${PRISMA_STUDIO_PORT}:5555

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: dockerfile
      target: dev
      args:
        - NODE_ENV=${NODE_ENV}
    volumes:
      - ./api/src:/app/src
    command: npm run dev
    ports:
      - "${API_NODE_PORT}:${API_NODE_PORT}"
    environment:
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - NODE_ENV

volumes:
  postgres: {}
