FROM node:16.15.1-alpine3.16 AS base
WORKDIR /app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY ./package*.json ./
COPY ./tsconfig.json ./

# ---- Development ----
FROM base AS dev
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

RUN npm install -g nodemon
RUN npm install
# RUN npm ci && npm cache clean --force
COPY . .
USER node
CMD npm run dev

# ---- Copy Files/Build ----
FROM base AS builder
COPY . .
# Build react/vue/angular bundle static files
USER node
RUN npm run build

# ---- Production ----
FROM base AS production
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}
# optional *install app dependencies*
# RUN npm install pm2 -g
RUN npm install --only=production
COPY --from=builder /app/dist ./dist
USER node
CMD node dist/index.js
